### ISSUE TITLE
ValueError: Input contains NaN.

### ISSUE THREAD

**Issue by superjdz** [TsingZ0/PFLlib#213]
![image](https://github.com/user-attachments/assets/f28e43ac-cff0-4aec-893e-78eeb7feb71a)

model: cnn dataset: mnist
when running scaffold and feddyn, the code raise the same error：ValueError: Input contains NaN.

Latter I will try to see if modify the model or check the data will help? 
Also, I will compare with the code in other FL code framework.

**Comment by TsingZ0** [comment]
I just test the code and no error occurs. Did you use the latest version? What was your command line when running this task?

**Comment by JACKSON1077** [comment]
question again! I am using the latest version both data generation and running.

**Comment by JACKSON1077** [comment]
> question again! I am using the latest version both data generation and running.


This problem may be caused by gradient explosion or gradient vanishing (I am not sure because I have not encountered problems like this). The version of FPLib I am using is before July 2024 (or maybe earlier). When I used the **FedRep** method to train **fasttext** on the **agnews(dir(0.1))** dataset(**nohup python -u main.py -lbs 10 -lr 0.01 -nc 20 -jr 1 -nb 4 -data agnews-dir1 -m fastText -gr 2000 -did 0 -go fastText -algo FedRep**), this error occurred in the 212th round (fixed). After debugging, I found that the embedding layer of self.model in this round had parameters, but the fully connected layer and the classifier layer had no parameters and no gradients (both NaN), so I judged that the gradient vanished or exploded. The same command does not appear in the current version (2024.11). I would like to ask, in dealing with the problem of gradient explosion or gradient vanishing, is there any optimization in the current version?

@TsingZ0

**Comment by JACKSON1077** [comment]
> > question again! I am using the latest version both data generation and running.
> 
> This problem may be caused by gradient explosion or gradient vanishing (I am not sure because I have not encountered problems like this). The version of FPLib I am using is before July 2024 (or maybe earlier). When I used the **FedRep** method to train **fasttext** on the **agnews(dir(0.1))** dataset(**nohup python -u main.py -lbs 10 -lr 0.01 -nc 20 -jr 1 -nb 4 -data agnews-dir1 -m fastText -gr 2000 -did 0 -go fastText -algo FedRep**), this error occurred in the 212th round (fixed). After debugging, I found that the embedding layer of self.model in this round had parameters, but the fully connected layer and the classifier layer had no parameters and no gradients (both NaN), so I judged that the gradient vanished or exploded. The same command does not appear in the current version (2024.11). I would like to ask, in dealing with the problem of gradient explosion or gradient vanishing, is there any optimization in the current version?
> 
> @TsingZ0




<img width="764" alt="屏幕截图 2024-11-20 141219" src="https://github.com/user-attachments/assets/110b5bf7-b38d-455d-a4b0-0cf031bbadaa">
